// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmmUJImsQPXAUrvPCWW1gnd2bWQwTMTHI',
    appId: '1:542081061872:web:0279de783acdc98bb88335',
    messagingSenderId: '542081061872',
    projectId: 'tig333-5eb08',
    authDomain: 'tig333-5eb08.firebaseapp.com',
    databaseURL: 'https://tig333-5eb08-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tig333-5eb08.appspot.com',
    measurementId: 'G-F858CBNRW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ3_5_t6KZZXV-sfLp2SwAfNCAYvbEd8U',
    appId: '1:542081061872:android:826f3154d9468fc3b88335',
    messagingSenderId: '542081061872',
    projectId: 'tig333-5eb08',
    databaseURL: 'https://tig333-5eb08-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tig333-5eb08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiFRUmPsRjoDy9SAcjz9ZKSYzcgkslWhE',
    appId: '1:542081061872:ios:e0aaac7ca8f47780b88335',
    messagingSenderId: '542081061872',
    projectId: 'tig333-5eb08',
    databaseURL: 'https://tig333-5eb08-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tig333-5eb08.appspot.com',
    iosBundleId: 'com.example.flutterFlame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiFRUmPsRjoDy9SAcjz9ZKSYzcgkslWhE',
    appId: '1:542081061872:ios:e7991dc87a24c4e1b88335',
    messagingSenderId: '542081061872',
    projectId: 'tig333-5eb08',
    databaseURL: 'https://tig333-5eb08-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tig333-5eb08.appspot.com',
    iosBundleId: 'com.example.flutterFlame.RunnerTests',
  );
}
